### ISSUE TITLE
Endpoint seems outdated

### ISSUE THREAD

**Issue by cson2701** [casdoor/casdoor-android-sdk#17]
According to the OpenID config, the endpoint of logging out should be `https://casdoor.xxx.com/api/logout`

Using the logout function provided by the Android SDK throws the following exception:
```
java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://casdoor.xxx.com/api/login/oauth/logout?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlcnQtYnVpbHQtaW4iLCJ0eXAiOiJKV1QifQ.eyxxxxxx&state=xxx}
```

**Comment by hsluoyz** [comment]
@cson2701 hi, can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@cson2701 you don't need to call Casdoor's logout API. Just destroy the session of the app
