### ISSUE TITLE
GetUserInfo hardcoded value

### ISSUE THREAD

**Issue by dshilovprpl** [casdoor/casdoor-android-sdk#18]
https://github.com/casdoor/casdoor-android-sdk/blob/0d1c52510390d4edf1749262b08398694f878bc9/library/src/main/java/org/casdoor/Casdoor.kt#L173

Should use data from config: `config.apiEndpoin`

**Comment by hsluoyz** [comment]
@dshilovprpl fixed by: https://github.com/casdoor/casdoor-android-sdk/commit/933164162f26dbe17bd8e119dd3bfdeed2285b88

**Comment by yuvalSure** [comment]
@hsluoyz thanks a lot for the fix. How can I get the updated code through a gradle dependency? previously I used:    implementation 'com.github.casdoor:casdoor-android-sdk:66141e0a4b'

**Comment by hsluoyz** [comment]
@yuvalSure v0.0.1 has been released here: https://mvnrepository.com/artifact/org.casbin/casdoor-android-sdk/0.0.1

For Gradle:

```
implementation group: 'org.casbin', name: 'casdoor-android-sdk', version: '0.0.1'
```
