### ISSUE TITLE
Setup GitHub Actions CI and semantic-release

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-android-sdk#6]
Like: https://github.com/casdoor/casdoor-java-sdk/pull/11

**Comment by hsluoyz** [comment]
@caoshengdong

**Comment by caoshengdong** [comment]
The main purpose of this CI script is to push to the Maven Repository, but it needs to be done using Gradle, which already contains the script to build and push to the Maven Repository, so we just need to let the CI script execute it.
